### ISSUE TITLE
How do you use this application?

### ISSUE THREAD

**Issue by antonjan** [jgibbard/iqtool#1]
Hi

I am struggling to get your tool working.

~/iqtool$ python3 ./iqgen.py  -t 1000 -fs 48000 -o iq_tone_int16_iq.iq -f int16 
usage: iqgen.py [-h] [-t TONE | -i | -r] [-fs SAMPLERATE] [-o FILENAME]
                [-f FORMAT] [-a AMPLITUDE] [-be] [-qi] [-p]
                samples
iqgen.py: error: the following arguments are required: samples

Can give me working example please?

**Comment by jgibbard** [comment]
Hi, you need to specify the number of samples you want to generate. This is the only non-optional argument. So in your example just put the number of samples at the very end. For example to generate 10000 samples you would use:
~/iqtool$ python3 ./iqgen.py -t 1000 -fs 48000 -o iq_tone_int16_iq.iq -f int16 10000
